apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  type: NodePort
  ports:
  - port: 80  # Port exposed within the cluster
    targetPort: 4000  # Port on the pods
    nodePort: 30000  # Port accessible externally 
  selector:
    app: helloworld
